config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "posts#index"

  resources :posts do
    resources :comments
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def email_required?
    false
  end
  
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
    before_action :authorize_user, only: [:edit, :update, :destroy]
    skip_before_action :verify_authenticity_token

    def authorize_user
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        unless current_user == @comment.user
          flash[:alert] = "You are not authorized to perform this action."
          redirect_to @post
        end
    end

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        @comment.user_id = current_user.id

        if @comment.save
            redirect_to post_path(@post)
          else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])

        if current_user == @comment.user
            @comment.destroy
            redirect_to @post, status: :see_other
        else
            flash[:alert] = "You are not authorized to delete this comment."
            redirect_to @post
        end
    end

    def edit
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        if current_user != @comment.user
          flash[:alert] = "You are not authorized to edit this comment."
          redirect_to @post
        end
    end

    def update
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])

        if current_user == @comment.user
            if @comment.update(comment_params)
                redirect_to post_path(@post)
            else
                flash.now[:alert] = "There was an error updating the comment."
                render :edit, status: :unprocessable_entity
            end
        else
            flash[:alert] = "You are not authorized to update this comment."
            redirect_to @post
        end
    end

    private
        def comment_params
            params
                .require(:comment)
                .permit(:body)
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def authorize_user
    @post = Post.find(params[:id])
    unless current_user == @post.user
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to @post
    end
  end  

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @categories = Category.all
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.category = Category.find(params[:post][:category_id])
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
    @categories = Category.all
    if current_user != @post.user
      flash[:alert] = "You are not authorized to edit this post."
      redirect_to @post
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.category = Category.find(params[:post][:category_id])

    if current_user == @post.user
      if @post.update(post_params)
        redirect_to @post
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash[:alert] = "You are not authorized to update this post."
      redirect_to @post
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if current_user == @post.user
      @post.destroy
      redirect_to root_path, status: :see_other
    else
      flash[:alert] = "You are not authorized to delete this post."
      redirect_to @post
    end
  end

  private
    def post_params
      params
        .require(:post)
        .permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  Comment by <%= comment.user.username %>
</p>

<% if current_user == comment.user %>
  <%= link_to 'Edit Comment', edit_post_comment_path(comment.post, comment) %>
  <%= button_to "Delete Comment", [comment.post, comment], method: :delete %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
  <div>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= react_component("Header", {}, {prerender: true}) %>

<h1>Edit Comment</h1>

<%= form_with model: [ @post, @comment ] do |form| %>
  <div>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CvwoForum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% post.errors.full_messages_for(:title).each do |message| %>
        <div>
            <%= message %>
        </div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% post.errors.full_messages_for(:body).each do |message| %>
        <div>
            <%= message %>
        </div>
    <% end %>
  </div>

  <div>
    <%= form.select :category_id, options_from_collection_for_select(@categories, "id", "name"), prompt: "Select a category" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= react_component("Header", {}, {prerender: true}) %>

<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<%= react_component("Header", {}, {prerender: true}) %>

<% if user_signed_in? %>
 <div> Welcome <%= current_user.username %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

<h1>Posts</h1>

<% if user_signed_in? %>
  <%= link_to "New Post", new_post_path %>
<% end %>

<ul>
  <% @posts.each do |post| %>
    <li>
        <%= link_to post.title, post %>
        [<%= post.category.name %>]
        [Created by <%= post.user.username %>]
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= react_component("Header", {}, {prerender: true}) %>

<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<%= react_component("Header", {}, {prerender: true}) %>

<% if user_signed_in? %>
 <div> Welcome <%= current_user.username %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

<h1><%= @post.title %></h1>

<p><%= @post.category.name %></p>

<p>Created by <%= @post.user.username %></p>

<p><%= @post.body %></p>

<% if current_user == @post.user %>
    <%= link_to "Edit Post", edit_post_path(@post) %>
    <%= button_to "Delete Post", @post, method: :delete %>
<% end %>

<h2>Comments</h2>
<%= render @post.comments %>

<% if user_signed_in? %>
    <h2>Add a comment:</h2>
    <%= render 'comments/form'%>
<% end %>